version: "3"

services:
  chainlink:
    image: smartcontract/chainlink:0.10.6
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.chainlink
    volumes:
      - ./chainlink:/chainlink
    ports:
      - 6688:6688
    command: local n -p /chainlink/config/password -a /chainlink/config/api
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.chainlink
    volumes:
      - ./chainlink:/chainlink
  external-ad:
    build: .
    restart: always
    ports:
      - 7654:7654
    command: yarn solink chainlink-external
    env_file:
      - .env